version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: finance_db
      POSTGRES_USER: manasisawant
      POSTGRES_PASSWORD: rishi2311
    ports:
      - "5432:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8002:8000"
    depends_on:
      - db
